### ISSUE TITLE
Possible project building on top of tbtc tornado

### ISSUE THREAD

**Issue by statelayer** [tbtctornado/frontend#1]
Hey, if you guys are interested to participate in building a yield farming system on top of your project to incentivize privacy, drop into the #tbtc-tornado-cash channel of the Keep Discord and we'll talk.  

https://discord.com/invite/wYezN7v 

We'd love to see you there ! :)

Sorry for leaving an issue, was my only way of communicating with you guys ! :D

**Comment by benesjan** [comment]
Hello LayerState, I don't currently have enough time to collaborate with you on the project but feel free to fork our codebase and let me know if you need anything. Cheers, Jan
